---
title: "MATH 3190 Lab 4"
author: "R Shiny (due 2/7/24)"
filters:
  - shinylive
---

# Step 09: Final App

```{shinylive-r}
#| standalone: true
#| viewerHeight: 600
library(shiny)
ui <- fluidPage(
  
  # Put a titlePanel here
  titlePanel("k-means clustering"),
  
  sidebarLayout(
    # Sidebar. Put your inputs inside the sidebarPanel
    sidebarPanel(
      selectInput('xcol', 'X Variable', names(iris)),
      selectInput('ycol', 'Y Variable', names(iris),
                  selected=names(iris)[[2]]),
      numericInput('clusters', 'Cluster count', 3,
                   min = 1, max = 9)
    ),
    
    # Main panel. put your output plot here
    mainPanel(
      plotOutput('plot1')
    )
  )
)

server <- function(input, output, session) {
  
  selectedData <- reactive({
    iris[, c(input$xcol, input$ycol)]
  })
  
  clusters <- reactive({
    kmeans(selectedData(), input$clusters)
  })
  
  output$plot1 <- renderPlot({
    palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
              "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))
    
    par(mar = c(5.1, 4.1, 0, 1))
    plot(selectedData(),
         col = clusters()$cluster,
         pch = 20, cex = 3)
    points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
  })
}

shinyApp(ui = ui, server = server)
```

# Problem 2 - R Shiny for mtcars

The `mtcars` data set was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). This data set is already built into **R**. You can load it by typing `data(mtcars)`. Once you do that, you should change the `cyl`, `vs`, `am`, `gear`, and `carb` variables to be factors rather than numeric.

Your job is to build an app that has the following:

-   A title for the app.
-   An input select box that lets the user specify which variable in the data set they are selecting.
-   An input select box that lets the user specify what type of plot to use, either a histogram, box plot, or bar plot.
-   The app should then output the plot of the variable that is selcted. The plot should have a nice color, a title, and easy to read axes.
-   If the variable is quantiative and a bar plot is selected, then a message should appear to the user indicating the wrong type of plot is selected.
-   Likewise, if the variable is categorical and a histogram or box plot is selected, then a message should appear to the user indicating the wrong type of plot is selected.

Some hints:

-   The app will need a `ui` element, a `server` function, and the last line should be `shinyApp(server = server, ui = ui)`.
-   Add items to your app one at a time and run it often to make sure things are working as expected.
-   You'll need both a `renderText()` and a `renderPlot()` function in the server.
-   `if` statements are very useful in these shiny apps.
-   The variable selected by the user will be saved as an object in `input$`. You should use the `reactive()` functions to save it as an object in the `server` function and then access it in the `render...()` functions by typing its name with parentheses `()` at the end. For example, if you save it as `var_select` then you will access it as `var_select()` in the `reactive()` functions.
-   In `ggplot`, we are used to calling the name of the variable we are plotting in the `aes()` function. However, the variable we are plotting is being chosen by the user and is reactive. You can access the variable you want by putting `mtcars` as the first argument in `ggplot` and then by putting `aes(x = .data[[var_select()]])`, if you saved your variable as `var_select` in the server function. That `.data` will refer back to whatever data set you entered into the `ggplot` function. So, it will look like `ggplot(mtcars, aes(x = .data[[var_select()]]))`. Of course, you can change that `x` to an `y` where appropriate.

One more thing about R Markdown. If you change the **R** code chunk option from `eval = F` to `eval = T` after building your app, the code will run, but the app will not be interactive. It is just a static file. You can make it interaction by adding `runtime: shiny` (not indented) to the bottom of the YAML (under the `editor_options:` section). If you save the file, the Knit button at the top should change to a play button that says "Run Document". If you click that, it will make the document interactive. You cannot save and share the output of document in this state, though.

```{r mtcars_app, eval = F, echo = T}
library(tidyverse)
library(shiny)

```
